### ISSUE TITLE
UNH split card not recognized

### ISSUE THREAD

**Issue by tooomm** [april/decklist#33]
~~The card [`Who/What/When/Where/Why`](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74358) isn't correctly recognized, even though its name is correct.~~
<br><pre>**Update:** https://github.com/april/decklist/issues/33#issuecomment-354401343
>With the UNS Oracle Update, it is now officially [`Who // What // Where // When // Why`](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74358)</pre>

<br>

![untitled](https://user-images.githubusercontent.com/9874850/33795629-76ab1388-dce5-11e7-9dd2-922336bacf8b.png)
Compare for yourself:
- https://www.decklist.org/?deckmain=1%20Who/What/When/Where/Why
- https://www.decklist.org/?deckmain=1%20Who%20//%20What%20//%20When%20//%20Where%20//%20Why

It's an error in your database creation. Because you handle that card the same as any other split card and therefore it ends up in your database with double `//` separation **with spaces** `"Side1 // Side2"`:
- `"who // what // when // where // why":{c:"S",b:"sml",m:98,n:"Who // What // When // Where // Why"}`<br>

But it should be single `/` separation **without spaces** `"Side1/Side2"` for that particular card:
- `"who/what/when/where/why":{c:"S",b:"sml",m:98,n:"Who/What/When/Where/Why"}`

<br>

That's actually the same issue with the Cockatrice app, because mtgjson (used as source for the card database) has no split cards but all single halves. In order to create a database one has to combine them to a single card with its combined names.
Problem is the unique and different naming scheme for the UNH split card in comparison to aftermath or fuse cards for example.

**Comment by ChaimW** [comment]
Actually, it is probably not a bad idea to make it so that a single slash gets the split card.
also the word to (as in Commit **to** Memory)

**Comment by tooomm** [comment]
The issue here is that the database has a wrong card name saved.
For the solution used in Cockatrice check this PR: https://github.com/Cockatrice/Cockatrice/pull/2949.

Your suggestion would be a smart addition to split cards in general @ChaimW.
But note that there is also the convention "Fire **and** Ice" for old split cards:
http://markrosewater.tumblr.com/post/159174592333/is-the-naming-convention-for-the-new-aftermath

**Comment by KBGrammer** [comment]
The convention that gatherer uses is that the split card Wear and Tear is "Wear // Tear", with the separator being " // ". That un-card is just a special case and has to be handled accordingly. Every other card uses the gatherer standard separator and most websites follow that convention. Tappedout is inconsistent in how they name them, with some cards being " / " and some not having spaces at all, but it does understand what you want if you feed "Wear // Tear" into that system.

I don't think that the gatherer convention should be abandoned because one card out of ~64 cards breaks it. Though if the system only exists to spit out a document that will be read by humans later as a decklist, then humans will know that "Wear/Tear" is the same as "Wear // Tear".

You probably want to behave like Tappedout does and be able to take "Wear/Tear", "Wear / Tear", "Wear//Tear", and "Wear // Tear" as inputs, though.

**Comment by ChaimW** [comment]
@KBGrammer I plan to add all of those, as I am currently working on it, in addition, I want to allow people to enter Commit to Memory & Fire and Ice, since people look at them that way. If I can manage it, I'd want to allow simply entering one word (e.g. Fire) and have the full card show up.

**Comment by ChaimW** [comment]
@tooomm With the UNS Oracle Update, it is now officially [`Who // What // Where // When // Why`](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74358)

**Comment by tooomm** [comment]
Is there an official announcement for that change/the oracle udpate? @ChaimW?
Can you link me somewhere? Which cards are affected?

**Comment by ChaimW** [comment]
https://twitter.com/EliShffrn/status/943227067180527616 is the best I can do.

**Comment by tooomm** [comment]
It looks like with the most recent card list updates by @april (https://github.com/april/decklist/commits/master) it's even completely broken now:

![broken](https://user-images.githubusercontent.com/9874850/35983563-8c933ab2-0cf2-11e8-85e2-51d20aad4fb1.png)

By the way: RIX seem to not work yet!

**Comment by april** [comment]
It’s working for me?

[image: image1.png]



On Feb 8, 2018, at 10:07 AM, tooomm <notifications@github.com> wrote:

It looks like with the most recent card list updates by @april
<https://github.com/april> (https://github.com/april/decklist/commits/master)
it's even completely broken now:

[image: broken]
<https://user-images.githubusercontent.com/9874850/35983563-8c933ab2-0cf2-11e8-85e2-51d20aad4fb1.png>

By the way: RIX seem to not work yet!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/april/decklist/issues/33#issuecomment-364160230>, or mute
the thread

**Comment by tooomm** [comment]
Attaching images via mail doesn't work. 😉 

On the live page www.decklist.org the UNH and RIX cards doesn't show up...
![norix](https://user-images.githubusercontent.com/9874850/35985350-c02ca81e-0cf6-11e8-8375-c5753a2d14a2.png)


Also tried with the version at master. Same result.

**Comment by april** [comment]
Trying putting a 1 before each card so that it knows the quantity that is
in your deck?

On Feb 8, 2018, at 10:38 AM, tooomm <notifications@github.com> wrote:

Attaching images via mail doesn't work. 😉

On the live page www.decklist.org the UNH and RIX cards doesn't show up...
[image: norix]
<https://user-images.githubusercontent.com/9874850/35985350-c02ca81e-0cf6-11e8-8375-c5753a2d14a2.png>

Also tried with the version at master. Same result.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/april/decklist/issues/33#issuecomment-364170599>, or mute
the thread

**Comment by tooomm** [comment]
So all issue got solved in the meantime and nobody realized.... hehe.

I'm really surprised there is no case handling or warning for missing quantities! 👎
