### ISSUE TITLE
Allow SCG formatted decklists

### ISSUE THREAD

**Issue by april** [april/decklist#8]
Wouldn't it be great if players could simply select WotC or SCG style decklists?  One checkmark is all that would be needed to switch back and forth between them.  Heck, we could even include the SCG waiver, if we were being ambitious.

http://8e8460c4912582c4e519-11fcbfd88ed5b90cfb46edba899033c9.r65.cf1.rackcdn.com/www/pdfs/Decklist.pdf

**Comment by Nightfirecat** [comment]
Is the copy+paste format consistent between browsers?

Regardless, do you have any examples handy? If not, I'll look around tomorrow and get some gists posted with text examples for testing.

**Comment by marumari** [comment]
Are you asking for an example of the SCG decklist?  As far as I know, copy/paste is consistent enough between browsers, but I’m not sure what you’re asking for with regards to that.

**Comment by Nightfirecat** [comment]
I'm just looking for examples of what the raw text looks like when a list is copied in specific browsers... For instance, the following are what I get when copy+pasting into np++ from a random SCG decklist (by copy+pasting the full text) on Firefox and Chrome:

* [Firefox](https://gist.github.com/Nightfirecat/1b4fc826f67fc013e437)
* [Chrome](https://gist.github.com/Nightfirecat/908f211d54d94f8cda23)

There's a number of spacing differences, so this may not be very feasible. That said, [it looks like they offer a MODO-ized version of the decklist](http://sales.starcitygames.com/deckdatabase/deck_files/79361-MODO.txt) that can already be parsed.

**Comment by marumari** [comment]
Oh!  I think you misunderstand what I was looking for in this.  I want to allow SCG style PDF files, like this:

http://8e8460c4912582c4e519-11fcbfd88ed5b90cfb46edba899033c9.r65.cf1.rackcdn.com/www/pdfs/Decklist.pdf

I’m not worried about copying and pasting.  :)  It’s a very long project to do, and I’m hoping to get SCG to sponsor it to get the work done.  Figuring out the coordinates for the WotC PDF took about 8-10 hours; this one will take a lot longer.

**Comment by Nightfirecat** [comment]
Ohhhh, I see. Apologies for misunderstanding, haha.

I'd definitely support this, though I'd imagine this would need SCG approval to use their design.

**Comment by marumari** [comment]
They’ve already given it, and they’re very excited for me to put in 10-20 hours of development for them for free.  :P

**Comment by Nightfirecat** [comment]
Ok, awesome.

We'll have to keep in mind that the fields / validation will be slightly different between formats, but shouldn't be too heavily impacted--we should be able to control those with a flag.

**Comment by Nightfirecat** [comment]
I did some work on this on my [scg-decksheet branch](https://github.com/Nightfirecat/decklist/tree/scg-decksheet), but it's far from finished. At this point, I've created a near-replica of [the SCG decklist sheet](http://static.starcitygames.com/www/pdfs/Decklist.pdf), though I've found a couple main issues:

1. I don't have the images. (not a big one, since I can grab those directly from a screencap of the PDF)
2. We don't have the font they use. This one's bigger, since not only is it necessary to get a more pixel-perfect match, but it'll also require upgrading the jsPDF version in order to allow adding new fonts via webfonts, or otherwise.
3. jsPDF doesn't support adding pages of different orientations [until v1.0.272](https://github.com/MrRio/jsPDF/issues/49#issuecomment-57177292), and [we're currently on v1.0.209](https://github.com/Nightfirecat/decklist/blob/scg-decksheet/js/jsPDF-master/bower.json#L3). As such, this'll require an upgrade in version to be completed as well. Until I change the version myself (was working away from internet connection this week), I won't have a second page ready to view.

That said, even if this version isn't pixel-perfect, it might be good enough. I wouldn't be a good judge (heh) of whether SCG should be involved in "OK"ing a final online version of the sheet.

In any event, I'd like to get *something* finished from this, as most of the work is already finished; all that's left is a couple more pixel adjustments, upgrading the jsPDF version, and arranging the additions into a clean set of commits.

**Comment by Nightfirecat** [comment]
Fixed point (3) - that was easy enough to do by just doing a straight replace of the jsPDF-master directory with what's up on GitHub now.

Of course, now Arial doesn't work as a font anymore, and the `addFont()` command doesn't seem to actually work. More investigation to follow, will post updates sometime, eventually.

**Comment by tooomm** [comment]
Is this still a goal to get this working?

>http://8e8460c4912582c4e519-11fcbfd88ed5b90cfb46edba899033c9.r65.cf1.rackcdn.com/www/pdfs/Decklist.pdf

The pdf isn't available anymore.

In Europe the SCG counterpart might be the MKM series: http://series.magiccardmarket.eu/, but I can't tell if they use their own registration sheets, too.

**Comment by Nightfirecat** [comment]
Looks like this is a better permalink: http://static.starcitygames.com/www/pdfs/Decklist.pdf

**Comment by april** [comment]
The time to lay these out in a PDF generate is quite considerable (like a half dozen hours or so), so unless SCG is willing to pay me to devote a bunch of time to it, I probably won't spend the time. If somebody wants to make a commit, I would happily accept it.

**Comment by Nightfirecat** [comment]
I've done some work on it, but ran into issues with horizontal/vertical page alignment, so put it aside. My current progress in at least getting the static layout done is here: https://nightfirecat.github.io/decklist/

**Comment by tooomm** [comment]
Understandable, if it is really that time consuming...
At least it's on the radar with an updated link again. Had no idea how theirs looks like!

**Comment by Nightfirecat** [comment]
I've been working on this a bit myself, since I got some recent motivation to work on it. Attached below is what I have currently working on my scg-decklist branch. The remaining tasks to finalize it are below, which I plan on completing in the coming weeks:

- [ ] Fix first page box alignment; sizes are mostly correct but boxes are slightly out of place
- [ ] **Add images** (need to find good-sized PNGs or vectors for all images included)
- [ ] Add layout logic for user-entered forms

[decklist.pdf](https://github.com/april/decklist/files/1849836/decklist-14.pdf)

**Comment by Nightfirecat** [comment]
I'm hoping to have this wrapped up and submitted in a PR by early next week. Once completed, this will close #8 (this issue), #38, and implement (supersede) #35, #39, and #40.

Anyone interested in the progress thus far can take a look at my scg-decksheet fork, which just implemented a full rewrite of the deck parsing functions to support the layout that will be needed for the maindeck sections of the SCG decksheet.

**Comment by april** [comment]
Awesome! Thank you! I’ll be back in town next Friday so I should be able to
review it then.  :)

On Apr 6, 2018, at 8:34 PM, Jordan <notifications@github.com> wrote:

I'm hoping to have this wrapped up and submitted in a PR by early next
week. Once completed, this will close #8
<https://github.com/april/decklist/issues/8> (this issue), #38
<https://github.com/april/decklist/issues/38>, and implement (supersede) #35
<https://github.com/april/decklist/pull/35>, #39
<https://github.com/april/decklist/pull/39>, and #40
<https://github.com/april/decklist/pull/40>.

Anyone interested in the progress thus far can take a look at my
scg-decksheet fork, which just implemented a full rewrite of the deck
parsing functions to support the layout that will be needed for the
maindeck sections of the SCG decksheet.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/april/decklist/issues/8#issuecomment-379429011>, or mute
the thread
